### ISSUE TITLE
GitHub 2 factor login

### ISSUE THREAD

**Issue by scj643** [NeuronRobotics/BowlerStudio#57]
### Installed Version

0.19.1
### OS type and version number

Windows Version 10.0.14393 Build 14393

Signing in when you have 2 factor enabled in GitHub doesn't work even when you use the right password it doesn't sign in.

**Comment by madhephaestus** [comment]
this may be a better issue to post in the underlying library im using:
https://github.com/kohsuke/github-api

All the authentication and login access is managed by that library. Id be happy to update my version of github-api to work well with 2 factor auth, as well as using the library to set up an oauth key for logging in in the future, rather than using the user/pass each time.

**Comment by scj643** [comment]
If a failed login returns `X-GitHub-OTP: required; :2fa-type` in the header we should mention https://github.com/settings/tokens and to make an OAuth token as your password.

**Comment by madhephaestus** [comment]
@kohsuke What are your thoughts on 2 factor auth for github-api?

**Comment by kohsuke** [comment]
I lack the context, what does github-api need to do? Can you kindly file that as an issue?

**Comment by madhephaestus** [comment]
this thread move to https://github.com/kohsuke/github-api/issues/292

**Comment by madhephaestus** [comment]
This issue was moved to CommonWealthRobotics/BowlerStudio#6
